In [1]:
import pandas as pd
import numpy as np

In [3]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC

In [64]:
lr = LogisticRegression(solver="liblinear",max_iter=100)
svc = LinearSVC(C=1.0)
rfc = RandomForestClassifier(n_estimators=100)

In [65]:
pima = pd.read_csv("https://raw.githubusercontent.com/PyDataWorkshop/datasets/master/pima.csv")

In [66]:
pima.head()

Preg   Gluc  Dias  Tric  2hSer   BM1   Diab  Age  Diab.1
0      6   148    72    35      0  33.6  0.627   50       1
1      1    85    66    29      0  26.6  0.351   31       0
2      8   183    64     0      0  23.3  0.672   32       1
3      1    89    66    23     94  28.1  0.167   21       0
4      0   137    40    35    168  43.1  2.288   33       1

In [67]:
pima.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Preg    768 non-null    int64  
 1   Gluc    768 non-null    int64  
 2   Dias    768 non-null    int64  
 3   Tric    768 non-null    int64  
 4   2hSer   768 non-null    int64  
 5   BM1     768 non-null    float64
 6   Diab    768 non-null    float64
 7   Age     768 non-null    int64  
 8   Diab.1  768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [68]:
pima.shape

(768, 9)

In [69]:
from sklearn.model_selection import train_test_split
train,test = train_test_split(pima,test_size=0.2,random_state=42)

In [70]:
train.shape

(614, 9)

In [71]:
test.shape

(154, 9)

In [72]:
train.head(5)

Preg   Gluc  Dias  Tric  2hSer   BM1   Diab  Age  Diab.1
60       2    84     0     0      0   0.0  0.304   21       0
618      9   112    82    24      0  28.2  1.282   50       1
346      1   139    46    19     83  28.7  0.654   22       0
294      0   161    50     0      0  21.9  0.254   65       0
231      6   134    80    37    370  46.2  0.238   46       1

In [73]:
train_feat = train.iloc[:,0:-1]
train_targ = train["Diab.1"]

In [74]:
train_targ

60     0
618    1
346    0
294    0
231    1
      ..
71     0
106    0
270    1
435    1
102    0
Name: Diab.1, Length: 614, dtype: int64

In [75]:
lr.fit(train_feat,train_targ)

LogisticRegression(solver='liblinear')

In [76]:
lr.score(train_feat,train_targ)

0.7703583061889251

In [77]:
test_feat = test.iloc[:,0:-1]
test_targ = test["Diab.1"]

In [79]:
test_targ

668    0
324    0
624    0
690    0
473    0
      ..
355    1
534    0
344    0
296    1
462    0
Name: Diab.1, Length: 154, dtype: int64

In [80]:
from sklearn.metrics import confusion_matrix

In [81]:
confusion_matrix(lr.predict(test_feat),test_targ)

array([[83, 21],
       [16, 34]])

In [83]:
confusion_matrix(lr.predict(train_feat),train_targ)

array([[359,  99],
       [ 42, 114]])

# RANDOM FOREST CLASSIFIER

In [84]:
rfc.fit(train_feat,train_targ)

RandomForestClassifier()

In [86]:
rfc.score(train_feat,train_targ)

1.0

In [87]:
rfc.score(test_feat,test_targ)

0.7597402597402597

In [88]:
preds = rfc.predict(test_feat)[:10]

In [89]:
preds

array([0, 0, 0, 0, 0, 1, 0, 1, 1, 1])

In [91]:
confusion_matrix(rfc.predict(train_feat),train_targ)

array([[401,   0],
       [  0, 213]])

In [92]:
confusion_matrix(rfc.predict(test_feat),test_targ)

array([[80, 18],
       [19, 37]])

# SVC CLASSIFIER

In [96]:
svc.fit(train_feat,train_targ)

/Users/aryaman/opt/anaconda3/lib/python3.9/site-packages/sklearn/svm/_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


LinearSVC()

In [97]:
svc.score(train_feat,train_targ)

0.6530944625407166

In [98]:
svc.score(test_feat,test_targ)

0.6428571428571429

In [100]:
confusion_matrix(svc.predict(train_feat),train_targ)

array([[401, 213],
       [  0,   0]])